apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bale-countries-check.fullname" . }}
  labels:
    {{- include "bale-countries-check.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bale-countries-check.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bale-countries-check.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config
            - /app/config.yaml
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "bale-countries-check.fullname" . }}
