apiVersion: v1
kind: Service
metadata:
  name: {{ include "bale-countries-check.fullname" . }}
  labels:
    {{- include "bale-countries-check.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "bale-countries-check.selectorLabels" . | nindent 4 }}
